DROP TABLE IF EXISTS prize;
CREATE TABLE prize(
    id INT(11) PRIMARY KEY not NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL ,
    name VARCHAR(255) NOT NULL,
    image VARCHAR(255) NOT NULL
)DEFAULT CHARSET=utf8;
