DROP TABLE IF EXISTS type;
CREATE TABLE type(
  id INT(11) PRIMARY KEY AUTO_INCREMENT,
  typename VARCHAR(255) NOT NULL
)DEFAULT CHARSET=utf8;
INSERT INTO type VALUES(1, '演唱会');
INSERT INTO type VALUES(2, '话剧');
INSERT INTO type VALUES(3, '音乐会');
INSERT INTO type VALUES(4, '舞蹈表演');
INSERT INTO type VALUES(5, '戏剧');
INSERT INTO type VALUES(6, '而同亲子');